language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    include:
        - php: 5.6
          env: DEPENDENCIES='dev' SYMFONY_VERSION='2.8.*@dev'
        - php: 5.6
          env: SYMFONY_VERSION='3.0.*@dev'
        - php: 7.1
          env: SYMFONY_VERSION='4.1.*'

before_install:
    - composer self-update # remove this once the Travis upgrade of February 2015 is deployed
    - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION}; fi;
    - wget -O phpunit.phar https://phar.phpunit.de/phpunit-4.8.phar

install: composer update $COMPOSER_FLAGS

script:
  - php phpunit.phar -v
  - php phpunit.phar
