language: php

env:
  global:
    - deps="no"
    - SYMFONY_VERSION=""
    - SYMFONY_DEPRECATIONS_HELPER="weak"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: SYMFONY_VERSION="3.0.*"
    - php: 7.0
      env: SYMFONY_VERSION="3.1.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 5.3
      env: SYMFONY_VERSION="2.3.*"

before_install:
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI_FILE
  - echo opcache.enable_cli = 1 >> $INI_FILE
  - echo session.gc_probability = 0
  - if [[ "SYMFONY_VERSION" == "2.8.*" || "SYMFONY_VERSION" == 3.* ]]; then export SYMFONY_DEPRECATIONS_HELPER="strict"; fi;
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text
